-- CreateTable
CREATE TABLE `REVENUE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORIGIN` VARCHAR(191) NOT NULL,
    `VALUE` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EXPENSE` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORIGIN` VARCHAR(191) NOT NULL,
    `VALUE` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
